Repository wecode-bootcamp-korea/11-Hipce-frontend, pull requests merged in 2020-08, with the labels that each got.

#4 [HIPCE] Update README.md
  README.md
Labels: Status: 리뷰 요청

#3 [이조은] Add: Footer 레이아웃 완료
  .eslintrc.json
  .vscode/settings.json
  package-lock.json
  package.json
  public/index.html
  src/Components/Footer.js
  src/Components/Footer.scss
  src/Pages/Main/Main.js
  src/Routes.js
  src/Styles/common.scss
  src/Styles/reset.scss
  src/index.js
Labels: Status: 리뷰 요청

#7 [이상훈] List페이지 레이아웃 및 일부기능 구현
  .vscode/settings.json
  package-lock.json
  public/images/aaa.jpg
  src/Pages/List/List.js
  src/Pages/List/List.scss
  src/Pages/List/Product.js
  src/Pages/List/Product.scss
  src/Pages/List/ProductFilter.js
  src/Pages/List/ProductFilter.scss
  src/Pages/List/ProductListBottom.js
  src/Pages/List/ProductListBottom.scss
  src/Pages/List/ProductNav.js
  src/Pages/List/ProductNav.scss
  src/Routes.js
Labels: Status: 수정 요청

#10 [이상훈] About페이지 레이아웃 초안
  src/Components/Footer.scss
  src/Pages/About/About.js
  src/Pages/About/About.scss
  src/Pages/List/Pallete.js
  src/Pages/List/Pallete.scss
  src/Routes.js
Labels: Status: 수정 요청, Status: 추가 기능 구현중

#1 [조은별] Add: 로그인 페이지 기능 구현
  .vscode/settings.json
  public/Images/social-facebook.png
  public/Images/social-kakao.png
  public/Images/social-naver.png
  src/Pages/Main/Main.js
  src/Pages/Sign/InputWithLabel.js
  src/Pages/Sign/InputWithLabel.scss
  src/Pages/Sign/Sign.js
  src/Pages/Sign/Sign.scss
  src/Pages/Sign/SignUp.scss
  src/Pages/Sign/Terms.js
  src/Pages/Sign/Terms.scss
  src/Pages/Sign/signUp.js
  src/Styles/reset.scss
  src/index.js
Labels: Status: 수정 요청

#6 [조은별] add: 회원가입 페이지 레이아웃 추가
  .vscode/settings.json
  src/Pages/Main/Main.js
  src/Pages/Sign/InputWithLabel.js
  src/Pages/Sign/InputWithLabel.scss
  src/Pages/Sign/Login.js
  src/Pages/Sign/Login.scss
  src/Pages/Sign/SignUp.js
  src/Pages/Sign/SignUp.scss
  src/Pages/Sign/Terms.js
  src/Pages/Sign/Terms.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#12 [이조은] Modify: 마스터 수정
  src/Components/Nav.js
  src/Components/Nav.scss
  src/Pages/Detail/Detail.js
  src/Pages/List/Product.js
  src/Pages/List/ProductNav.js
  src/Pages/Main/Main.js
  src/Pages/Main/MainCollection.js
  src/Pages/Main/MainEdition.js
  src/Pages/Main/MainHinceAtelier.js
  src/Pages/Sign/Login.js
  src/Pages/Sign/Login.scss
  src/Pages/Sign/SignUp.js
  src/Routes.js
Labels: Status: 리뷰 요청

#13 [조은별] Modify: 로그인 페이지 수정 완료
  src/Pages/Main/Main.js
  src/Pages/Sign/InputWithLabel.scss
  src/Pages/Sign/Login.js
  src/Pages/Sign/Login.scss
  src/Pages/Sign/SignUp.js
  src/Pages/Sign/SignUp.scss
  src/Pages/Sign/Terms.js
  src/Pages/Sign/Terms.scss
  src/config.js
Labels: Status: 리뷰 요청

#22 [이조은] Refactor: 멘토님 리뷰 반영
  src/Components/Nav.js
  src/Components/Nav.scss
Labels: Status: 리뷰 요청

#19 [이상훈]Add: List페이지 기능 추가구현
  public/data/productMockdata.json
  src/Pages/About/About.js
  src/Pages/Detail/Comment.js
  src/Pages/Detail/CommentList.js
  src/Pages/Detail/Detail.js
  src/Pages/Detail/DetailMain.js
  src/Pages/Detail/Review.js
  src/Pages/Detail/Showmore.js
  src/Pages/List/List.js
  src/Pages/List/List.scss
  src/Pages/List/Pallete.js
  src/Pages/List/Pallete.scss
  src/Pages/List/Product.js
  src/Pages/List/Product.scss
  src/Pages/List/ProductFilter.js
  src/Pages/List/ProductListBottom.js
  src/Pages/List/ProductListBottom.scss
  src/Pages/List/ProductNav.js
  src/Pages/List/ProductNav.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#9 [이상훈]Add: 장바구니 추가기능 구현
  package-lock.json
  package.json
  public/data/mockDataForShopping.json
  src/Pages/Shoppingbag/ItemList.js
  src/Pages/Shoppingbag/Shoppingbag.js
  src/Pages/Shoppingbag/Shoppingbag.scss
  src/Routes.js
  src/index.js
Labels: Status: Accepted

#17 [이상훈]Add: Modal창 레이아웃 완료
  .eslintrc.json
  package-lock.json
  src/Components/Nav.js
  src/Pages/List/Pallete.js
  src/Pages/Main/Main.js
  src/Pages/Search/Search.js
  src/Pages/Search/Search.scss
  src/Routes.js
Labels: Status: 수정 요청

#14 [김영지]Modify: collection 페이지 레이아웃 수정
  src/Pages/Collection/Collection.js
  src/Pages/Collection/Collection.scss
  src/Pages/Detail/Detail.scss
  src/Routes.js
Labels: Status: 수정 요청

#20 [이조은] Modify: 멘토님 리뷰 반영
  src/Pages/Main/Components/ImgBox.js
  src/Pages/Main/Components/ImgBox.scss
  src/Pages/Main/Components/MainBestSeller.js
  src/Pages/Main/Components/MainBestSeller.scss
  src/Pages/Main/Components/MainBestSellerSlider.js
  src/Pages/Main/Components/MainBestSellerSlider.scss
  src/Pages/Main/Components/MainCollection.js
  src/Pages/Main/Components/MainCollection.scss
  src/Pages/Main/Components/MainEdition.js
  src/Pages/Main/Components/MainEdition.scss
  src/Pages/Main/Components/MainHinceAtelier.js
  src/Pages/Main/Components/MainHinceAtelier.scss
  src/Pages/Main/Components/MainNewProduct.js
  src/Pages/Main/Components/MainNewProduct.scss
  src/Pages/Main/Components/MainNewProductSlider.js
  src/Pages/Main/Components/MainNewProductSlider.scss
  src/Pages/Main/Components/MainNewProductSliderData.js
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Pages/Main/MainBestSellerSlider.js
  src/Pages/Main/MainNewProductSlider.js
Labels: Status: 리뷰 요청

#23 [이조은] Modify: 오류 수정
  src/Components/Nav.js
  src/Routes.js
Labels: Status: 리뷰 요청

#15 [조은별] Modify: 회원가입 페이지 기능구현
  src/Components/Footer.js
  src/Pages/Sign/InputWithLabel.js
  src/Pages/Sign/InputWithLabel.scss
  src/Pages/Sign/SignUp.js
  src/Pages/Sign/SignUp.scss
  src/Pages/Sign/Terms.js
Labels: Status: 리뷰 요청

#21 [김영지]Modify: conflict해결
  public/Images/checker.png
  public/data/data.json
  src/Components/Nav.js
  src/Pages/Detail/Color.js
  src/Pages/Detail/ColorList.js
  src/Pages/Detail/ColorList.scss
  src/Pages/Detail/Comment.js
  src/Pages/Detail/Comment.scss
  src/Pages/Detail/CommentList.js
  src/Pages/Detail/CountLike.js
  src/Pages/Detail/CountLike.scss
  src/Pages/Detail/Detail.js
  src/Pages/Detail/Detail.scss
  src/Pages/Detail/DetailMain.js
  src/Pages/Detail/DetailMain.scss
  src/Pages/Detail/ProductDetail.js
  src/Pages/Detail/ProductDetail.scss
  src/Pages/Detail/Review.js
  src/Pages/Detail/Review.scss
  src/Pages/Detail/ReviewFrame.js
  src/Pages/Detail/Showmore.scss
  src/Pages/List/Product.js
  src/Routes.js
Labels: Status: 리뷰 요청

#24 [이조은] Add: 제품 사진 클릭 시 상세페이지 이동
  src/Pages/Main/Components/ImgBox.js
  src/Pages/Main/Components/ImgBox.scss
  src/Pages/Main/Components/MainBestSellerSlider.js
  src/Pages/Main/Components/MainNewProductSlider.js
Labels: Status: 리뷰 요청

#27 [이조은] Modify: Nav 애니메이션 및 scss 변수 지정
  src/Components/Nav.js
  src/Components/Nav.scss
Labels: Status: 리뷰 요청

#25 [이조은] Add: 버튼에 alert창 추가
  src/Components/Nav.js
  src/Pages/Checkout/Account.scss
  src/Pages/Checkout/Checkout.js
  src/Pages/Checkout/Checkout.scss
  src/Pages/Checkout/Components/Account.js
  src/Pages/Checkout/Components/Account.scss
  src/Pages/Checkout/Components/Card.js
  src/Pages/Checkout/Components/Card.scss
  src/Pages/Checkout/Components/OrderSummary.js
  src/Pages/Checkout/Components/OrderSummary.scss
  src/Pages/Checkout/Components/Transfer.js
  src/Pages/Checkout/Components/Transfer.scss
  src/Pages/Checkout/Components/Virtual.js
  src/Pages/Checkout/Components/Virtual.scss
  src/Pages/Checkout/Transfer.scss
  src/Pages/Checkout/Virtual.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#26 [이상훈]Modify: List 페이지 기능 일부 조정
  public/data/productMockdata.json
  src/Components/Nav.scss
  src/Pages/About/About.js
  src/Pages/Detail/Color.js
  src/Pages/Detail/Detail.js
  src/Pages/Detail/DetailMain.js
  src/Pages/Detail/ProductDetail.js
  src/Pages/List/List.js
  src/Pages/List/Product.js
  src/Pages/List/ProductFilter.js
  src/Pages/List/ProductFilter.scss
  src/Pages/List/ProductNav.js
  src/Pages/Shoppingbag/ItemList.js
  src/Pages/Shoppingbag/Shoppingbag.js
  src/Pages/Shoppingbag/Shoppingbag.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#28 [이조은] Modify: 오류 수정
  src/Components/Nav.scss
Labels: Status: 리뷰 요청

#29 Modify: 최종 발표 위한 최종 오류 수정
  public/data/mockDataForShopping.json
  public/index.html
  src/Components/Nav.js
  src/Components/Nav.scss
  src/Pages/Checkout/Checkout.js
  src/Pages/Collection/Collection.js
  src/Pages/Detail/Detail.js
  src/Pages/Detail/DetailMain.js
  src/Pages/List/ProductFilter.js
  src/Pages/Main/Components/ImgBox.js
  src/Pages/Main/Components/MainCollection.js
  src/Pages/Main/Components/MainNewProduct.js
  src/Pages/Main/Components/MainNewProductSlider.js
  src/Pages/Search/Search.js
  src/Pages/Search/Search.scss
  src/Pages/Shoppingbag/Shoppingbag.js
  src/Pages/Sign/Login.js
  src/Pages/Sign/SignUp.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청
